variables:
  IMAGE_NAME: hatem1396/hello
  IMAGE_TAG: IDS-app-1.0

stages:
  - build
  - deploy


build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - rm -rf venv
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG


deploy:
 stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - chmod 400 $SSH_KEY
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY azureuser@20.107.244.31 "
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG "
